services:
  - type: web
    name: stylish-blog
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false

