services:
  # Web Service (Next.js Application)
  - type: web
    name: blogsite-web
    env: node
    rootDir: .
    buildCommand: |
      chmod +x ./render-build.sh && ./render-build.sh
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: ADMIN_EMAIL
        value: admin@yourblogsite.com
    healthCheckPath: /api/health